on:
    schedule:
        - cron: '0 */8 * * *'  # Run every 8 hours
    workflow_dispatch:       # Allows manual triggering from the GitHub Actions tab

  
name: Build and deploy documentation
  
  # borrowed from https://github.com/teorth/pfr/blob/master/.github/workflows/push.yml
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build_project:
      runs-on: ubuntu-latest
      name: Build project
      steps:
        - name: Checkout project
          uses: actions/checkout@v4
          with:
            repository: HEPLean/PhysLean
            fetch-depth: 0
  
        - name: Install Graphviz
          run: sudo apt-get update && sudo apt-get install -y graphviz
  
        - name: Verify Graphviz Installation
          run: dot -V
        ##################
        # Remove this section if you don't want docs to be made
#        - name: Install elan
#          run: |
#            set -o pipefail
#            curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
#            ~/.elan/bin/lean --version
#            echo "$HOME/.elan/bin" >> $GITHUB_PATH
#  
#        - name: Get Mathlib cache
#          run: lake -Kenv=dev exe cache get || true
#  
#        - name: Build project
#          run: lake -Kenv=dev build PhysLean
#  
#        - name: make TODO list
#          run : lake exe TODO_to_yml mkFile
#  
#        - name: make list of informal proofs and lemmas
#          run : lake exe informal mkFile mkDot mkHTML
#  
#        - name: make stats page
#          run : lake exe stats mkHTML
#  
#        - name: make notes
#          run : lake exe notes
#  
#        - name: Generate svg from dot
#          run : dot -Tsvg -o ./docs/graph.svg ./docs/InformalDot.dot
#  
#        - name: Replace template file with custom
#          run : cp ./scripts/Template.lean .lake/packages/doc-gen4/DocGen4/Output/Template.lean
#  
#        - name: Get doc cache
#          uses: actions/cache@v3
#          with:
#            path: |
#              .lake/build/doc/Init
#              .lake/build/doc/DocGen4
#              .lake/build/doc/Aesop
#              .lake/build/doc/Lake
#              .lake/build/doc/Batteries
#              .lake/build/doc/Lean
#              .lake/build/doc/Std
#              .lake/build/doc/Mathlib
#              .lake/build/doc/declarations
#              !.lake/build/doc/declarations/declaration-data-PhysLean*
#            key: MathlibDoc-${{ hashFiles('lake-manifest.json') }}
#            restore-keys: |
#              MathlibDoc-
  
#        - name: Build documentation
#          run: lake -Kenv=dev build PhysLean:docs
  
#        - name: Copy documentation to `docs/docs`
#          run: |
#            mv .lake/build/doc docs/docs
        #End Section
        ##################
        
        - name: Upload documentation artifact
          uses: actions/upload-artifact@v4
          with:
            name: documentation
            path: docs/
            retention-days: 90
  